# Generated by Django 3.1.5 on 2021-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortenerApp', '0002_auto_20210130_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
