# Generated by Django 3.1.5 on 2021-02-05 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortenerApp', '0003_shortenedurl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlclick',
            name='click_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlclick',
            name='related_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clicks', to='UrlShortenerApp.shortenedurl', verbose_name='Соответствующая ссылка'),
            preserve_default=False,
        ),
    ]
