# Generated by Django 3.1.5 on 2021-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210228_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='avatars/', verbose_name='user_image'),
        ),
    ]
